services:
  mailhog-service:
    image: mailhog/mailhog
    container_name: mailhog-service
    restart: always
    volumes:
      - ./data/maildir:/maildir
    environment:
      - MH_STORAGE=maildir
    ports:
      - ${SMTP_PORT}:1025
      - ${HTTP_PORT}:8025

  minio-service:
    image: bitnami/minio:latest
    container_name: minio-service
    ports:
      - ${MINIO_WEB_PORT}:9000
      - ${MINIO_API_PORT}:9001
    networks:
      - minio_network
    volumes:
      - "./data/minio_data:/data"
    environment:
      - MINIO_ROOT_USER=${MINIO_ROOT_USER}
      - MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD}
      - MINIO_DEFAULT_BUCKETS=${MINIO_DEFAULT_BUCKETS}

  postgres-service:
    image: postgres:latest
    container_name: postgres-service
    ports:
      - ${POSTGRES_PORT}:5432
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - ./data/postgres_data:/var/lib/postgresql/data

  adminer-service:
    image: adminer
    container_name: adminer-service
    restart: always
    ports:
      - ${ADMINER_PORT}:8080

networks:
  minio_network:
    driver: bridge

volumes:
  minio_data:
    driver: local
