name: flowcast
services:
  catalog-storage-service:
    image: mongo
    restart: always
    ports:
      - ${CATALOG_STORAGE_PORT}:27017
    volumes:
      - ./data/mongo_data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${CATALOG_STORAGE_ROOT_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${CATALOG_STORAGE_ROOT_PASSWORD}
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/test --quiet
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 40s

  # song-storage-service:
  #   image: bitnami/minio:latest
  #   ports:
  #     - ${SONG_STORAGE_WEB_PORT}:9000
  #     - ${SONG_STORAGE_API_PORT}:9001
  #   networks:
  #     - minio_network
  #   volumes:
  #     - "./data/minio_data:/data"
  #   environment:
  #     - MINIO_ROOT_USER=${SONG_STORAGE_ROOT_USER}
  #     - MINIO_ROOT_PASSWORD=${SONG_STORAGE_ROOT_PASSWORD}
  #     - MINIO_DEFAULT_BUCKETS=${SONG_STORAGE_DEFAULT_BUCKETS}