services:
  minio-service:
    image: bitnami/minio:latest
    ports:
      - ${MINIO_WEB_PORT}:9000
      - ${MINIO_API_PORT}:9001
    networks:
      - minio_network
    volumes:
      - "./data/minio_data:/data"
    environment:
      - MINIO_ROOT_USER=${MINIO_ROOT_USER}
      - MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD}
      - MINIO_DEFAULT_BUCKETS=${MINIO_DEFAULT_BUCKETS}
    # command: serve`r --console-address ":9001" /data
    # healthcheck:
    #   test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
    #   interval: 30s
    #   timeout: 20s
    #   retries: 3

  postgres-service:
    image: postgres:latest
    ports:
      - ${POSTGRES_PORT}:5432
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - ./data/postgres_data:/var/lib/postgresql/data

  adminer-service:
    image: adminer
    restart: always
    ports:
      - ${ADMINER_PORT}:8080

networks:
  minio_network:
    driver: bridge

volumes:
  minio_data:
    driver: local
