networks:
  minio_network:
    driver: bridge

volumes:
  minio_data:
    driver: local

services:
  minio-storage:
    image: bitnami/minio:latest
    ports:
      - ${WEB_PORT}:9000
      - ${API_PORT}:9001
    networks:
      - minio_network
    volumes:
      - "minio_data:/data"
    environment:
      - MINIO_ROOT_USER=${MINIO_ROOT_USER}
      - MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD}
      - MINIO_DEFAULT_BUCKETS=${MINIO_DEFAULT_BUCKETS}
    command: server --console-address ":9001" /data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3
  # TODO: finish this
  proxy-service:
    image: .
