# helmfile.yaml
repositories:
  - name: bitnami
    url: https://charts.bitnami.com/bitnami
  - name: elastic
    url: https://helm.elastic.co
  - name: redpanda
    url: https://charts.redpanda.com/
  - name: minio
    url: https://charts.min.io/
  - name: ingress-nginx
    url: https://kubernetes.github.io/ingress-nginx
  - name: prometheus-community
    url: https://prometheus-community.github.io/helm-charts
  - name: grafana
    url: https://grafana.github.io/helm-charts
  - name: varnish
    url: https://charts.softonic.io

releases:
  # NGINX Ingress Controller y API Gateway Consolidado
  - name: nginx
    namespace: default
    chart: ./charts/nginx
    version: 18.2.1
    values:
      - ./charts/nginx/values.yaml

  # Varnish
  - name: varnish
    namespace: varnish
    chart: ./charts/varnish
    version: 0.18.9
    values:
      - ./charts/varnish/values.yaml

  # Redpanda
  - name: redpanda
    namespace: redpanda
    chart: redpanda/redpanda
    version: 5.9.5
    values:
      - replicaCount: 3

  # MinIO
  - name: minio
    namespace: storage
    chart: minio/minio
    version: 8.0.14
    values:
      - accessKey: minioadmin
        secretKey: minioadmin
      - persistence:
          enabled: true
          size: 10Gi
      - replicas: 3


  # PostgreSQL
  - name: postgresql
    namespace: databases
    chart: bitnami/postgresql
    version: 11.18.0
    values:
      - postgresqlPassword: "postgres123"
      - persistence:
          enabled: true
          size: 10Gi

  # Elasticsearch
  - name: elasticsearch
    namespace: search
    chart: elastic/elasticsearch
    version: 7.17.9
    values:
      - replicas: 1
      - cluster:
          initial_master_nodes: ["node-1"]
      - resources:
          requests:
            cpu: "500m"
            memory: "1Gi"
          limits:
            cpu: "1"
            memory: "2Gi"

  # Prometheus
  - name: prometheus
    namespace: monitoring
    chart: prometheus-community/prometheus
    version: 25.27.0
    values:
      - ./charts/monitoring/prometheus/values.yaml

  # Grafana
  - name: grafana
    namespace: monitoring
    chart: grafana/grafana
    version: 8.5.2
    values:
      - "./charts/monitoring/grafana/values.yaml"

  # Prometheus Adapter
  - name: prometheus-adapter
    namespace: monitoring
    chart: prometheus-community/prometheus-adapter
    version: 4.11.0
    values:
      - ./charts/monitoring/prometheus-adapter/values.yaml

  # MongoDB (para 5 microservicios)
  - name: mongodb-service1
    namespace: databases
    chart: bitnami/mongodb
    version: 15.6.26
    values:
      - replicaSet:
          enabled: false
        auth:
          rootPassword: "admin123"
          username: "service1"
          password: "password1"
          database: "service1db"

  - name: mongodb-service2
    namespace: databases
    chart: bitnami/mongodb
    version: 15.6.26
    values:
      - replicaSet:
          enabled: false
      - auth:
          rootPassword: "admin123"
          username: "service2"
          password: "password2"
          database: "service2db"

  - name: mongodb-service3
    namespace: databases
    chart: bitnami/mongodb
    version: 15.6.26
    values:
      - replicaSet:
          enabled: false
      - auth:
          rootPassword: "admin123"
          username: "service3"
          password: "password3"
          database: "service3db"

  - name: mongodb-service4
    namespace: databases
    chart: bitnami/mongodb
    version: 15.6.26
    values:
      - replicaSet:
          enabled: false
      - auth:
          rootPassword: "admin123"
          username: "service4"
          password: "password4"
          database: "service4db"

  - name: mongodb-service5
    namespace: databases
    chart: bitnami/mongodb
    version: 15.6.26
    values:
      - replicaSet:
          enabled: false
      - auth:
          rootPassword: "admin123"
          username: "service5"
          password: "password5"
          database: "service5db"

  # Microservicios Backend (Ejemplo para Service1)
  - name: service1
    namespace: backend
    chart: ./charts/service1
    values:
      - image:
          repository: harbor.harbor.local/library/service1
          tag: latest
        env:
          DATABASE_URL: "mongodb://service1:password1@mongodb-service1.databases.svc.cluster.local:27017/service1db"


  # Repetir para los otros microservicios...
