# helmfile.yaml
repositories:
  - name: stable
    url: https://charts.helm.sh/stable
  - name: bitnami
    url: https://charts.bitnami.com/bitnami
  - name: elastic
    url: https://helm.elastic.co
  - name: redpanda
    url: https://charts.redpanda.com/
  - name: minio
    url: https://charts.min.io/
  - name: ingress-nginx
    url: https://kubernetes.github.io/ingress-nginx
  - name: prometheus-community
    url: https://prometheus-community.github.io/helm-charts

releases:
  # NGINX Ingress Controller y API Gateway Consolidado
  - name: nginx
    namespace: default
    chart: ./charts/nginx
    version: 0.1.0
    values:
      - ./charts/nginx/values.yaml

  # Varnish
  - name: varnish
    namespace: varnish
    chart: ./charts/varnish
    version: 0.1.0
    values:
      - ./charts/varnish/values.yaml

  # Redpanda
  - name: redpanda
    namespace: redpanda
    chart: redpanda/redpanda
    version: 0.1.0
    values:
      - replicaCount: 3

  # MinIO
  - name: minio
    namespace: storage
    chart: minio/minio
    version: 8.0.14
    values:
      - accessKey.password: minioadmin
        secretKey.password: minioadmin
      - persistence:
          enabled: true
          size: 10Gi
      - replicas: 3

  # PostgreSQL
  - name: postgresql
    namespace: databases
    chart: bitnami/postgresql
    version: 11.18.0
    values:
      - global:
          postgresql:
            postgresqlPassword: "postgres123"
      - persistence:
          enabled: true
          size: 10Gi

  # Elasticsearch
  - name: elasticsearch
    namespace: search
    chart: elastic/elasticsearch
    version: 7.17.9
    values:
      - replicas: 1
      - minimumMasterNodes: 1
      - resources:
          requests:
            cpu: "500m"
            memory: "1Gi"
          limits:
            cpu: "1"
            memory: "2Gi"

  # Prometheus
  - name: prometheus
    namespace: monitoring
    chart: prometheus-community/prometheus
    version: 14.6.0
    # values:
    #   - ./charts/monitoring/prometheus/templates/values.yaml

  # Grafana
  - name: grafana
    namespace: monitoring
    chart: prometheus-community/grafana
    version: 6.17.4
    # values:
    #   - "./charts/monitoring/grafana/templates/values.yaml"

  # Prometheus Adapter
  - name: prometheus-adapter
    namespace: monitoring
    chart: prometheus-community/prometheus-adapter
    version: 2.18.0
    # values:
    #   - ./charts/monitoring/prometheus-adapter/templates/values.yaml

  # MongoDB (para 5 microservicios)
  - name: mongodb-service1
    namespace: databases
    chart: bitnami/mongodb
    version: 10.26.6
    values:
      - replicaSet.enabled: false
      - auth.rootPassword: "admin123"
      - auth.username: "service1"
      - auth.password: "password1"
      - auth.database: "service1db"

  - name: mongodb-service2
    namespace: databases
    chart: bitnami/mongodb
    version: 10.26.6
    values:
      - replicaSet.enabled: false
      - auth.rootPassword: "admin123"
      - auth.username: "service2"
      - auth.password: "password2"
      - auth.database: "service2db"

  - name: mongodb-service3
    namespace: databases
    chart: bitnami/mongodb
    version: 10.26.6
    values:
      - replicaSet.enabled: false
      - auth.rootPassword: "admin123"
      - auth.username: "service3"
      - auth.password: "password3"
      - auth.database: "service3db"

  - name: mongodb-service4
    namespace: databases
    chart: bitnami/mongodb
    version: 10.26.6
    values:
      - replicaSet.enabled: false
      - auth.rootPassword: "admin123"
      - auth.username: "service4"
      - auth.password: "password4"
      - auth.database: "service4db"

  - name: mongodb-service5
    namespace: databases
    chart: bitnami/mongodb
    version: 10.26.6
    values:
      - replicaSet.enabled: false
      - auth.rootPassword: "admin123"
      - auth.username: "service5"
      - auth.password: "password5"
      - auth.database: "service5db"

  # Microservicios Backend (Ejemplo para Service1)
  - name: service1
    namespace: backend
    chart: ./charts/service1
    values:
      - image.repository: harbor.harbor.local/library/service1
        image.tag: latest
      - env:
          DATABASE_URL: "mongodb://service1:password1@mongodb-service1.databases.svc.cluster.local:27017/service1db"

  # Repetir para los otros microservicios...
