apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "varnish.fullname" . }}-config
  labels:
    {{- include "varnish.labels" . | nindent 4 }}
data:
  default.vcl: |
    {{ .Values.config.vcl | indent 4 }}
