{{- if .Values.hpa.enabled }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "varnish.fullname" . }}-hpa
  namespace: {{ .Release.Namespace }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "varnish.fullname" . }}
  minReplicas: {{ .Values.hpa.minReplicas }}
  maxReplicas: {{ .Values.hpa.maxReplicas }}
  metrics:
    {{- range .Values.hpa.metrics }}
    - type: {{ .type }}
      {{- if eq .type "Resource" }}
      resource:
        name: {{ .resource.name }}
        target:
          type: {{ .resource.target.type }}
          averageUtilization: {{ .resource.target.averageUtilization }}
      {{- else if eq .type "Pods" }}
      pods:
        metric:
          name: {{ .pods.metric.name }}
        target:
          type: {{ .pods.target.type }}
          averageValue: "{{ .pods.target.averageValue }}"
      {{- end }}
    {{- end }}
{{- end }}
