POST /register HTTP/1.1
Accept-Encoding: gzip, deflate, br
Connection: keep-alive
Content-Length: 331
User-Agent: HTTPie/3.2.2
Accept: application/json, */*;q=0.5
Content-Type: application/json
Host: localhost:4100

{"username": "Jorge", "email": "jorge@gmail.com", "password": "12345", "fullname": "Jorge Osorio", "birthdate": "1975-08-19T23:15:30.000Z", "gender": "male", "phone": "323423423423", "emailNotif": true, "smsNotif": true, "socialLinks": [{"platform": "facebook", "url": "facebook.com"}, {"platform": "github", "url": "github.com"}]}