apiVersion: v1
kind: Service
metadata:
  name: {{ include "nginx.fullname" . }}
  labels:
    {{- include "nginx.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.ports.http }}
      targetPort: {{ .Values.service.ports.http }}
      protocol: TCP
      name: http
    - port: {{ .Values.service.ports.https }}
      targetPort: {{ .Values.service.ports.https }}
      protocol: TCP
      name: https
    - port: {{ .Values.service.ports.api }}
      targetPort: {{ .Values.service.ports.api }}
      protocol: TCP
      name: api
  selector:
    app: {{ include "nginx.name" . }}
