# config/secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: global-secrets
  namespace: backend
type: Opaque
data:
  DATABASE_PASSWORD_SERVICE1: cGFzc3dvcmQx # "password1" en base64
  DATABASE_PASSWORD_SERVICE2: cGFzc3dvcmQy # "password2" en base64
  # Añade más secretos según sea necesario
